---
- hosts: all
  gather_facts: no
  any_errors_fatal: true
  #max_fail_percentage: 30
  connection: local
  collections:
  - f5networks.f5_modules
  
  vars_prompt:
  - name: f5_username
    prompt: "Enter F5 Username"
    private: no
    default: "{{ lookup('env','USER') }}"
    when: f5_username is not defined
  - name: f5_password
    prompt: "Enter F5 Password"
    when: f5_password is not defined
  tasks:

#  - name: Set authorized key took from file
#    authorized_key:
#      user: Aymen Ben Aouicha
#      state: present
#      key: "{{ lookup('file', '/Users/benaouicha/.ssh/id_rsa.pub') }}"
    
  - name: Get Software Volume Information
    bigip_device_info:
      gather_subset:
        - software-volumes
      provider: "{{ provider }}"
    register: sv
  
  - name: Get Current Version
    set_fact:
      current_version: "{{ item.version }}"
      current_boot_loc: "{{ item.name }}"
    when: item.active == "yes"
    with_items: "{{ sv.software_volumes }}"
  
  - name: Identify Hosts That Require Upgrade
    set_fact:
      wants_upgrade: True
    when: not new_image is search(current_version)
  
  - name: Identify Hosts That Don't Require Upgrade
    set_fact:
      wants_upgrade: False
    when: new_image is search(current_version)
  